language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install nose codecov

script:
 - nosetests --with-coverage --cover-package=dolfyn

after_success:
 - codecov

branches:
  only:
    - master
